# Generated by Django 3.2.12 on 2023-04-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('file', models.FileField(upload_to='uploads/')),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('reading', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
