# Generated by Django 3.2.12 on 2023-04-14 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filesupload', '0002_auto_20230414_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='file',
            new_name='files',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='mpan',
            field=models.CharField(default=0, max_length=22),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='reading',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
